# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{q-ruby-driver}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip Dodds", "John Shields"]
  s.date = %q{2011-05-08}
  s.default_executable = %q{q-ruby-driver}
  s.description = %q{A Ruby interface to Q database from Kx Systems}
  s.email = %q{philip.dodds at me dot com}
  s.executables = ["q-ruby-driver"]
  s.extra_rdoc_files = [
    "README.markdown",
    "README.txt"
  ]
  s.files = [
    "lib/q-ruby-driver.rb",
    "lib/q-ruby-driver/q_connection.rb",
    "lib/q-ruby-driver/q_exception.rb",
    "lib/q-ruby-driver/q_io.rb",
    "lib/q-ruby-driver/q_message.rb"
  ]
  s.homepage = %q{http://github.com/pdodds/q-ruby-driver}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A pure Ruby implementation of the Q IPC protocol}
  s.test_files = [
    "spec/q-ruby-driver_spec.rb",
    "spec/spec_helper.rb",
    "test/test_connection.rb",
    "test/test_helper.rb",
    "test/test_io.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<true>, [">= 0"])
      s.add_development_dependency(%q<true>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<true>, [">= 0"])
      s.add_dependency(%q<true>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<true>, [">= 0"])
    s.add_dependency(%q<true>, [">= 0"])
  end
end

